# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12test_service.proto\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\x14\n\x12GetPositionRequest\"(\n\x13GetPositionResponse\x12\x11\n\x01p\x18\x01 \x01(\x0b\x32\x06.Point2M\n\x0fPositionService\x12:\n\x0bGetPosition\x12\x13.GetPositionRequest\x1a\x14.GetPositionResponse\"\x00\x62\x06proto3')
)




_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Point.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Point.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=51,
)


_GETPOSITIONREQUEST = _descriptor.Descriptor(
  name='GetPositionRequest',
  full_name='GetPositionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=73,
)


_GETPOSITIONRESPONSE = _descriptor.Descriptor(
  name='GetPositionResponse',
  full_name='GetPositionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='p', full_name='GetPositionResponse.p', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=115,
)

_GETPOSITIONRESPONSE.fields_by_name['p'].message_type = _POINT
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['GetPositionRequest'] = _GETPOSITIONREQUEST
DESCRIPTOR.message_types_by_name['GetPositionResponse'] = _GETPOSITIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'test_service_pb2'
  # @@protoc_insertion_point(class_scope:Point)
  ))
_sym_db.RegisterMessage(Point)

GetPositionRequest = _reflection.GeneratedProtocolMessageType('GetPositionRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPOSITIONREQUEST,
  __module__ = 'test_service_pb2'
  # @@protoc_insertion_point(class_scope:GetPositionRequest)
  ))
_sym_db.RegisterMessage(GetPositionRequest)

GetPositionResponse = _reflection.GeneratedProtocolMessageType('GetPositionResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETPOSITIONRESPONSE,
  __module__ = 'test_service_pb2'
  # @@protoc_insertion_point(class_scope:GetPositionResponse)
  ))
_sym_db.RegisterMessage(GetPositionResponse)



_POSITIONSERVICE = _descriptor.ServiceDescriptor(
  name='PositionService',
  full_name='PositionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=117,
  serialized_end=194,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPosition',
    full_name='PositionService.GetPosition',
    index=0,
    containing_service=None,
    input_type=_GETPOSITIONREQUEST,
    output_type=_GETPOSITIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POSITIONSERVICE)

DESCRIPTOR.services_by_name['PositionService'] = _POSITIONSERVICE

# @@protoc_insertion_point(module_scope)
